### ISSUE TITLE
Getting better results with z3 4.7.1 compared to 4.6.0

### ISSUE THREAD

**Issue by asgeir386** [microsoft/ivy#40]
Summary: The 4.6.0 version of z3 produces the following error message, while 4.7.1 and 4.8.5 run without an issue. The ivy_to_cpp seems to be compatible with 4.7.1, but as previously noted 4.8.5 isn't
Details:when running a regression for the IVy models, I get the following error message with z3 4.6.0 both on MacOS Mojave and Linux. The Python executable grows in size to 50+GB (on MacOS) before this error message is displayed. The regression runs clean with z3 versions 4.7.1 and 4.8.5

What I don't know is if someone else is seeing IVy issues with using z3 4.7.1 (which was chosen based on being the next release after 4.6.0 see https://github.com/Z3Prover/z3/releases)

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ivy_check", line 11, in <module>
    load_entry_point('ms-ivy==0.1', 'console_scripts', 'ivy_check')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 696, in main
    check_module()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 675, in check_module
    check_isolate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 544, in check_isolate
    summarize_isolate(mod)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 522, in summarize_isolate
    if not check_safety_in_state(mod,ag,fail,report_pass=False):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 331, in check_safety_in_state
    return check_fcs_in_state(mod,ag,post,[Checker(lg.Or(),report_pass=report_pass)])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_check.py", line 299, in check_fcs_in_state
    model = itr.small_model_clauses(clauses,ffcs,shrink=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_transrel.py", line 555, in small_model_clauses
    return get_small_model(cls,ivy_logic.uninterpreted_sorts(),[],final_cond=final_cond,shrink=shrink)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 1101, in get_small_model
    res = decide(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 1028, in decide
    res = s.check() if atoms == None else s.check(atoms)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/z3/z3.py", line 6246, in check
    r = Z3_solver_check_assumptions(self.ctx.ref(), self.solver, num, _assumptions)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/z3/z3core.py", line 3402, in Z3_solver_check_assumptions
    _elems.Check(a0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/z3/z3core.py", line 1328, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: Overflow encountered when expanding vector

**Comment by kenmcmil** [comment]
Interesting. Can you try that regression with the option macro_finder=false?

**Comment by asgeir386** [comment]
Added the macro_finder=false to ivy_check

ivy_check diagnose=true debug=true trace=true macro_finder=false file.ivy

Produces the same results, the overflow message

I should have mentioned before that the overflow happens when IVy is processing an assert and that the run-time image for 4.7.1 is about 400MB when the assert passes and as I mentioned before the run-time image on 4.6.0 balloons to 50+GB before the overflow

**Comment by kenmcmil** [comment]
Thanks. There was a memout associated with the macro finder, so I wondered if that was it. I will bring ivy up to date with the z3 4.7.1 API.

**Comment by asgeir386** [comment]
I downloaded the master branch on 8/15

I did notice that when I add complete=fo to the ivy_check command line the run-time drops down to < 2min from close to 10min

Without the complete=fo the fragment check does pass i.e. the model only uses the decidable fragment
