### ISSUE TITLE
Trouble installing Ivy

### ISSUE THREAD

**Issue by J-Savela** [Microsoft/ivy#5]
I'm having trouble installing and running Ivy following the instructions. I have installed the prerequisites and am using Python 2.7.12. I cloned the Master branch and tried running `sudo python setup.py install`. I get 
```
  File "setup.py", line 12
    install_requires=[
                   ^
SyntaxError: invalid syntax
```
The setup.py file contains:
```
from setuptools import setup, find_packages

setup(name='ms_ivy',
      version='0.1',
      description='IVy verification tool',
      url='http://github.com/microsoft/ivy',
      author='IVy team',
      author_email='nomail@example.com',
      license='MIT',
      packages=find_packages(),
      include_package_data={'ivy':['include/*.ivy','include/*.h']}
      install_requires=[
          'ply',
          'pygraphviz',
          'tarjan'
      ],
      entry_points = {
        'console_scripts': ['ivy=ivy.ivy:main','ivy_check=ivy.ivy_check:main','ivy_to_cpp=ivy.ivy_to_cpp:main','ivy_show=ivy.ivy_show:main',],
        },
      zip_safe=False)

```
At first I thought that the line starting "include_package_data = ..." seems to be missing a comma. After fixing this and running `sudo python setup.py install` I get:
```
error in ms_ivy setup command: 'include_package_data' must be a boolean value (got {'ivy': ['include/*.ivy', 'include/*.h']})

```
Next I thought that perhaps the line was supposed to just be commented out or something and tried installing Ivy again with the line commented out. This time installing worked.

Trying to run the client_server_example I ran into more trouble though, which may or may not be related (My knowledge of Python is quite limited). I navigated to the `/doc/examples` folder and ran `ivy ui=cti client_server_example.ivy`. The window opened up fine, but when I click `Invariant-> Check induction` I get the following error and nothing happens in the Ivy window.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_cti.py", line 167, in check_inductiveness
    res = ag.check_bounded_safety(post, _get_model_clauses)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 357, in check_bounded_safety
    res = self.bmc(fail,true_clauses(),_get_model_clauses=_get_model_clauses,bound=bound)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 335, in bmc
    bmc_res = history_satisfy(history,state,_get_model_clauses,final_cond=error_cond)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_interp.py", line 578, in history_satisfy
    final_cond
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_transrel.py", line 566, in satisfy
    model = _get_model_clauses(post,final_cond=final_cond)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_cti.py", line 163, in <lambda>
    final_cond = final_cond
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 849, in get_small_model
    s.add(clauses_to_z3(clauses))
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 349, in clauses_to_z3
    z3_clauses = [conj_to_z3(cl) for cl in clauses.fmlas]
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 346, in conj_to_z3
    return formula_to_z3(cl)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 386, in formula_to_z3
    z3_formula = formula_to_z3_int(fmla)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 356, in formula_to_z3_int
    return atom_to_z3(fmla)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 324, in atom_to_z3
    return apply_z3_func(pred,tup)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_solver.py", line 222, in apply_z3_func
    _args, sz = z3._to_ast_array(tup)
AttributeError: 'module' object has no attribute '_to_ast_array'
```

I am using Ubuntu 16.04.2 LTS.

**Comment by J-Savela** [comment]
Now I saw the pull request. Apparently `include_package_data=...` should actually be `package_data=...`. This seems to help with the installation, but the problem with running the example still persists.

**Comment by J-Savela** [comment]
I have managed to get Ivy to run now, but I am still not quite sure what the underlying issue is as my proficiency with Python is limited. The problem I get when running `ivy ui=cti ***` seems to be that the z3py import isn't functioning correctly. I did some testing in the Python REPL: 
```
>>> import z3
>>> z3._to_ast_array
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '_to_ast_array'
>>> z3
<module 'z3' from '/usr/lib/python2.7/dist-packages/z3/__init__.py'>
>>> z3.z3
<module 'z3.z3' from '/usr/lib/python2.7/dist-packages/z3/z3.py'>
>>> z3.z3._to_ast_array
<function _to_ast_array at 0x7ff42a4d4cf8>
```
And:
```
>>> from z3 import *
>>> z3
<module 'z3.z3' from '/usr/lib/python2.7/dist-packages/z3/z3.py'>
```

In the file `ivy_solver.py` the library is imported using `import z3`, but the methods are called from z3 which solves to `__init__.py` on my machine, whereas z3.z3 actually solves to `z3.py`. I changed the import statement in `ivy_solver.py` to `from z3 import *`, which fixed the problem. 

Again, I don't know if this is a bug in z3 or Ivy or my own Python setup as I don't know how importing Python modules is expected to work.

**Comment by kenmcmil** [comment]
Try this:

    >>> import z3
    >>> z3.init("libz3.so")

If this works without an error then z3 is loading successfully (if on windows, it should be "libz3.dll").

**Comment by kenmcmil** [comment]
I'm guessing the problem is that the Z3 python API has changed and IVy hasn't kept up. I'll do some testing an try to see which releases of Z3 are compatible.

**Comment by kenmcmil** [comment]
I would suggest trying Z3 release 4.4.2. That works for me on Ubuntu 16.04.

**Comment by kenmcmil** [comment]
Also, I fixed the error in setup.py. You might want to pull the change and re-run it as some of the tutorial examples require files that you will miss by commenting out that line.

**Comment by J-Savela** [comment]
Thanks for the replies!

Running the above commands I get an error saying the file does not exists:
```
>>> import z3
>>> z3.init("libz3.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/z3/z3core.py", line 52, in init
    _lib = ctypes.CDLL(PATH)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jarkko/libz3.so: cannot open shared object file: No such file or directory
```

I will pull the fixed setup file next and try rolling back to 4.4.2 on Z3.

**Comment by kenmcmil** [comment]
That means that libz3.so is not in a place where python can find it. On my system it is installed in /usr/local/lib and /usr/local/lib/python2.7/site-packages.

**Comment by J-Savela** [comment]
I also tried loading the file from the actual directory and that works out fine. So is it a path variable issue?
```
>>> import z3
>>> z3.init("libz3.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/z3/z3core.py", line 52, in init
    _lib = ctypes.CDLL(PATH)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jarkko/Ivy/ivy/doc/examples/libz3.so: cannot open shared object file: No such file or directory
>>> z3.init("/usr/lib/libz3.so")
>>> z3.init("/usr/lib/python2.7/dist-packages/z3/lib/libz3.so")
```

**Comment by J-Savela** [comment]
Looking at the folders now I see that most python packages are installed in /usr/lib/python2.7 whereas only IVy along with a few other packages are installed in /usr/local/lib/python2.7.

**Comment by J-Savela** [comment]
I have been digging around and I suspect that the reason for my issues is the fact that Z3 modifed the package structure for Python bindings recently. Check out this closed issue on the Z3 repo:[https://github.com/Z3Prover/z3/pull/630](url).

Before the change you could simply do `import z3`, and that would import everything in z3.py (like _to_ast_array() method). Nowadays the the z3***.py files reside in a folder named z3. The problem is that on my setup the __init__.py file does not manage to import anything from z3.py. It does manage to import z3core.py, z3consts.py etc. To call functions from z3.py, I need to do `import z3` and `z3.z3.<fname>(...)`.

**Comment by J-Savela** [comment]
I switched to Z3 version 4.4.1, since I could not find a release tagged 4.4.2. In fact I couldn't find any release between 4.4.1 and 4.5.0. in the Z3 github repo. Switching to 4.4.1. I can now call the z3.py functions after simply importing z3, like Ivy does. This didn't fix all of the problems though. When I click "show reachable states" in the GUI, I still get an exception: 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui.py", line 245, in show_reachable_states
    self.ui_parent.add(self.reachable_tree)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui.py", line 306, in reachable_tree
    for s in self.g.domain.unders[0:1]:
AttributeError: 'Module' object has no attribute 'unders'

```

**Comment by J-Savela** [comment]
I have experienced some more issues with the GUI. I wrote some of my own example protocols and during working on one the system and clicking "Minimize" to automatically generalize the CTI, I got the following exceptions:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_util.py", line 106, in destroy_then_aux
    command()
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_util.py", line 173, in <lambda>
    action = destroy_then(dlg,lambda command=command, e=e: command(e.get()))
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_util.py", line 192, in <lambda>
    action = lambda s: command(_convert_to_int(s,minval,maxval))
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_cti.py", line 402, in <lambda>
    verbose=verbose, add_to_crg=add_to_crg)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_cti.py", line 457, in bmc_conjecture
    post = ag.execute(step_action, None, None, 'ext')
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 192, in execute
    poststate = self.post_state(op,prestate,abstractor)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 161, in post_state
    s = concrete_post(op.update(pre_state.domain,pre_state.in_scope),pre_state)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_interp.py", line 198, in concrete_post
    cons = compose_state_action(state.value,axioms,update,check=context.check)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_transrel.py", line 424, in compose_state_action
    raise ActionFailed(pre_test,trans)
ActionFailed
```
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_ui_cti.py", line 489, in minimize_conjecture
    post = ag.execute(step_action, None, None, 'ext')
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 192, in execute
    poststate = self.post_state(op,prestate,abstractor)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_art.py", line 161, in post_state
    s = concrete_post(op.update(pre_state.domain,pre_state.in_scope),pre_state)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_interp.py", line 198, in concrete_post
    cons = compose_state_action(state.value,axioms,update,check=context.check)
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.1-py2.7.egg/ivy/ivy_transrel.py", line 424, in compose_state_action
    raise ActionFailed(pre_test,trans)
ActionFailed
```

Perhaps the TKinter API has also changed in some way that's causing this trouble.
