### ISSUE TITLE
quantified assignment bad syntax leads to stack trace

### ISSUE THREAD

**Issue by larafranciulli** [microsoft/ivy#88]
Ivy crashes instead of reporting the syntax error.

```
#lang ivy1.7

type t

relation r(X:t)

action catch_bug = {
    forall X. r(X) := false;
}
```

Got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/ivy_check", line 11, in <module>
    load_entry_point('ms-ivy', 'console_scripts', 'ivy_check')()
  File "/home/lara/ivy/ivy/ivy_check.py", line 792, in main
    ivy_init.source_file(sys.argv[1],ivy_init.open_read(sys.argv[1]),create_isolate=False)
  File "/home/lara/ivy/ivy/ivy_init.py", line 72, in source_file
    ivy_load_file(f,**kwargs)
  File "/home/lara/ivy/ivy/ivy_compiler.py", line 2063, in ivy_load_file
    ivy_compile(decls,**kwargs)
  File "/home/lara/ivy/ivy/ivy_compiler.py", line 1996, in ivy_compile
    check_definitions(mod)
  File "/home/lara/ivy/ivy/ivy_compiler.py", line 1589, in check_definitions
    for s in sub.modifies():
  File "/home/lara/ivy/ivy/ivy_actions.py", line 395, in modifies
    while n.rep.name in ivy_module.module.destructor_sorts:
AttributeError: 'ForAll' object has no attribute 'rep'
```

**Comment by kenmcmil** [comment]
Fixed in commit 45a4151. Thanks!
